name: Cloud-resume-Github-actions
on:
  push:
    branch: [main]
jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

      - name: Copy files to the website with the AWS CLI
        run: aws s3 sync . s3://deborahoni.com
     
      